# Generated by Django 3.1.1 on 2020-12-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='due_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
