# Generated by Django 3.1.3 on 2020-11-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='class_code',
            field=models.CharField(default='0000000', max_length=10),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='section',
            field=models.CharField(default='Third Year', max_length=100),
        ),
    ]
