# Generated by Django 3.1.3 on 2020-11-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201114_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='submission_file',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
