# Generated by Django 3.1.1 on 2020-11-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_submissions_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='submitted_on_time',
            field=models.BooleanField(default=True),
        ),
    ]
