# Generated by Django 3.1.3 on 2020-11-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201119_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='submission_file',
            field=models.FileField(upload_to='documents'),
        ),
    ]
